server:
  port: 9001
spring:
  application:
    name: cloud-provider-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.80.131:8848
    gateway:
      routes:
        - id : user-router
          uri: http://127.0.0.1:9001
          predicates :
            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
  datasource:
    name: cloud_user
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://192.168.80.131:3306/cloud_user?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 1qaz
    type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/r_migration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl