server:
  port: 8888

spring:
    application:
      name: cloud-config-gateway
    cloud:
      gateway:
        enabled: true
        routes:
          - id : cloud-provider-user
            uri : http://localhost:9001
            predicates :
              - Path=/user/**
        discovery:
          locator:
            enabled: false
            lower-case-service-id: true
      nacos:
        discovery:
          server-addr: 192.168.80.131:8848

